Activated modal review
zarutskaalina/project-team-11 pull request #24
Opened 2023-06-21 15:47 UTC by ellenvasilek

2023-06-21 16:55 UTC, AntKhom commented
в классе .review-card-img надо исправить, а то у тебя картинка при 320 рх  съезжает
left: 50%;
transform: translate(-50%);
![image](https://github.com/zarutskaalina/project-team-11/assets/129000861/0930e5f1-7ede-4f1a-b315-a08602e1c055)

2023-06-21 16:58 UTC, AntKhom commented on src/partials/overlay-form-review.html
> +    <h4 class="review-modal-title">LEAVE A REVIEW ABOUT <span class="review-modal-title-org">OUR
тут ABOUT на второй строке, может нужен <br>

2023-06-21 17:01 UTC, AntKhom requested changes
С модалкой все отлично
,только ABOUT и картинки в моб версии

2023-06-21 17:31 UTC, ellenvasilek commented on src/partials/overlay-form-review.html
> -    <h4 class="review-modal-title">LEAVE A REVIEW ABOUT <span class="review-modal-title-org">OUR
Здесь перенести About в мобильной версии не выходит. Ширина заголовка задана верно. Я ещё подумаю над ним, но пока так

2023-06-22 04:28 UTC, AntKhom approved these changes

2023-06-22 05:59 UTC, merged